### ISSUE TITLE
Can't push in a separate branch

### ISSUE THREAD

**Issue by LOISGALLAUD** [flegh113/FxWordlist#3]
I want to contribute, made modifications in my own branch but I can't
`git push origin <my_branch>`

I got this output :
```bash
ERROR: Permission to flegh113/FxWordlist.git denied to LOISGALLAUD.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by flegh113** [comment]
Hello,

It seems you encountered an error because you tried to push your changes directly to my repository, for which you don't have write access. To contribute, please follow these steps:

1. Fork the repository : This creates a copy in your GitHub account.
2. Create a new branch in your fork and make your changes there.
3. Push your branch to your forked repository.
4. Submit a pull request (PR) : Go to your fork on GitHub, click "Compare & pull request," and propose your changes.
